components:
  parameters:
    userId:
      name: id
      in: path
      required: true
      type: integer
      description: The user ID.
    postId:
      name: id
      in: path
      required: true
      type: integer
      description: The post ID.
    imageName:
      name: file
      in: path
      required: true
      type: string
      description: The name of the uploaded image.
    pageCount:
      name: page
      in: query
      type: integer
    pageSize:
      name: limit
      in: query
      type: integer
    sortField:
      name: sort
      in: query
      type: string
      description: The property of the posts to sort.
    sortOrder:
      name: order
      in: query
      description: The order to sort the property of posts. Must be either `asc` or `desc`
      schema:
        type: string
        enum: [ asc, desc ]
